# Workflow Name
name: Tests Passing
# Set Event Which Triggers Workflow
on:
  push:
    branches:
      - main

jobs:
  Auto Test:
    # Using Ubuntu (other options exist but Ubuntu is most common)
    runs-on: ubuntu-latest
    container:
      # Using Node JS Version 22
      image: node:22
    steps:
      # Checkout Code
      - uses: actions/checkout@v3
        with:
          node-version: 22

      - name: Run Tests
        run: | 
          npm ci
          npm test

      - name: Run Build
        run: npm run build
